# Generated by Django 5.2.8 on 2025-12-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='unit_cost_at_sale',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
