# Generated by Django 5.2.8 on 2025-12-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_salerecord_unit_cost_at_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='order_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
