# Generated by Django 5.2.8 on 2025-12-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_salerecord_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_name',
            field=models.CharField(blank=True, default='IMS', max_length=100),
        ),
    ]
