# Generated by Django 5.2.8 on 2025-12-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_profile_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
